### PR TITLE
Update README with scaffold requirements

### PR DESCRIPTION
**Pull request by MicheleNL**
When I wanted to deploy the scaffold on a different environment I noticed some requirements and thought it would be a good idea to include them in the README.

### CODE REVIEW

**Review by harmenjanssen — APPROVED** [review]
LGTM

**Review by schoenkaft — CHANGES_REQUESTED** [review]
Hmm, I'd like to disagree. This is supposed to be an 'open scaffold', and I don't think those two should be a requirement at all.

---

ACF isn't required, and all calls should be wrapped in conditionals. See `Grrr\Acf\Setup`. If any new functionality is added that breaks it, it should be fixed. A lot of stuff was ported back recently, so it makes sense that some stuff might've been forgotten.

Assuming that you're referring to the new Twig\Functions, I'd prefer that those are prefixed with something like:
```php
public function get_acf_option(string $name, string $prefix) {
    if (!function_exists('get_field')) {
        return;
    }
    return get_field(str_replace(' ', '_', "{$prefix}_{$name}"), 'option');
}
```

Usually all `get_field` calls are in 'in-project' code, but in this case we moved some functionality to the scaffold. 

---

About the `The server needs to run PHP version 7.1 and php71-php-fpm.`, I thinks that's quite a specific and bold statement for the scaffold? For us it differs from server and project as well.

I assume you're referring to the `:fpm_reload` task in the Capistrano config? It's just an example (like a lot in the config/project is). The requirement would also be that you would have passwordless sudo control over that specific command. Might be better to comment that task out (and maybe add a comment), instead of enforcing a specific (and soon to be outdated) PHP version?

---

I like the reasoning, but I don't think it's the right solution for these two problems.

**Comment by schoenkaft** [comment]
I think we could close this one? The two issues creating these 'requirements' have been fixed, reviewed and merged. I've created a PR (https://github.com/grrr-amsterdam/wordpress-scaffold/pull/17) which adds a section with actual 'requirements' since that was indeed missing.

**Comment by MicheleNL** [comment]
Yes! I'm closing this one

**Pull request closed without merging**
